CLASS zrap110_bp_bookingtp_atti DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zrap110_r_traveltp_atti .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zrap110_bp_bookingtp_atti IMPLEMENTATION.
ENDCLASS.
