CLASS zrap110_calc_trav_elem_atti DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zrap110_calc_trav_elem_atti IMPLEMENTATION.
ENDCLASS.
